/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronal
 */
public class Buscar extends javax.swing.JPanel {

    Connection con;
    Statement st;
    
    
    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        con= MySQL.Conectar();
        llenarTituloTabla();
        
    }

    
    void llenarTituloTabla(){
        try{
            String titulos[] = {"Equipo", "Numero de serie", "Sucedido", "Aula", "Detalles", "Ingresado por", "Fecha de registro", "Estado"};
            DefaultTableModel model = new DefaultTableModel(null, titulos);
            tblBuscar.setModel(model);
            
        }catch(Exception e){
            
        }
    }
    
void llenarBusqueda(String numSerie) {
    try {
        String estado= "Desactivo";
        // Define los títulos de las columnas
        String titulos[] = {"Equipo", "Numero de serie", "Sucedido", "Aula", "Detalles", "Ingresado por", "Fecha de registro", "Estado"};
        DefaultTableModel model = new DefaultTableModel(null, titulos);

        // Consulta SQL para obtener los datos deseados
        String query = "SELECT c.Equipo, dr.Num_serie, dr.Id_aula, a.Nom_aula, dr.Detalle_reporte, " +
                       "emp.Nombres, dr.Fecha_registro, dr.Estado_activo " +
                       "FROM detalle_reporte dr " +
                       "JOIN componentes c ON dr.Id_equipo = c.Id_equipo " +
                       "JOIN aulas a ON dr.Id_aula = a.Id_aula " +
                       "JOIN empleados emp ON dr.Id_empleado = emp.Id_empleado " +
                       "WHERE dr.Num_serie = ?";

        // Crear un PreparedStatement para ejecutar la consulta
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, numSerie);
        ResultSet rs = ps.executeQuery();

        // Recorrer los resultados y llenar el modelo de la tabla
        while (rs.next()) {
            String fila[] = new String[8];
            if (rs.getInt("Estado_activo")!=0) {
                estado ="Activo";
            }
            fila[0] = rs.getString("Equipo"); // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[1] = rs.getString("Num_serie");    // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[2] = rs.getString("Id_aula");      // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[3] = rs.getString("Nom_aula");  // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[4] = rs.getString("Detalle_reporte"); // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[5] = rs.getString("Nombres");       // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[6] = rs.getString("Fecha_registro"); // Verifica que coincida con el nombre de la columna en tu base de datos
            fila[7] = estado; // Verifica que coincida con el nombre de la columna en tu base de datos
            model.addRow(fila);
        }

        // Asigna el modelo a la JTable
        tblBuscar.setModel(model);

    } catch (Exception e) {
        
        JOptionPane.showMessageDialog(null, "Error al buscar los datos: " + e.getMessage());
    }
}


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscar = new javax.swing.JTable();
        txtNumSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        tblBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBuscar);

        txtNumSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumSerieKeyTyped(evt);
            }
        });

        jLabel2.setText("INGRESE EL NUMERO DE SERIE QUE DESEA BUSCAR");

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarBusqueda(txtNumSerie.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNumSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSerieKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String texto = txtNumSerie.getText();
        if(!(Character.isLetter(c) || c=='-')) evt.consume();
        if (texto.length() >= 11) {
        
        evt.consume(); 
        }
    }//GEN-LAST:event_txtNumSerieKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuscar;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
