/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ronal
 */
public class Equipo1 extends javax.swing.JPanel {

     
    Connection con;
    Statement st;
    
    /**
     * Creates new form Equipo1
     */
    public Equipo1() {
        
        initComponents();
        
        llenarComboEquipos();
        
    }
    
        void llenarComboEquipos(){
        try {
            con = MySQL.Conectar();
            
            String s = "select *from componentes";
            String equipo = "";
            
            st = con.createStatement();
            ResultSet rs = st.executeQuery(s);
            cmbEquipos1.removeAll();
            while (rs.next()) {                
                equipo = rs.getString("Equipo");
                cmbEquipos1.addItem(equipo);
            }
        } catch (Exception e) {
            System.out.println("error 1: "+ e.getMessage());
        }
    }
        
        
    public int devolverEquipoNuevo(){
           
           return  cmbEquipos1.getSelectedIndex()+1;
       }

    public String devolverEquipoNuevoEnString(){
           
           return   (String) cmbEquipos1.getSelectedItem();
       }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbEquipos1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cmbEquipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cmbEquipos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEquipos1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
